### ISSUE TITLE
Version 2.2 fails with ClassCastException

### ISSUE THREAD

**Issue by gianluca1606** [fillumina/krasa-jaxb-tools#13]
Hello @fillumina 

After upgrading to apache CXF 4.0.4 and also upgrading other dependencies the CXF Plugin fails to generato due to some error in the krasa-jaxb-tools.

```[WARNING] Exception in thread "main" org.apache.cxf.tools.common.ToolException: java.lang.ClassCastException: class com.sun.xml.xsom.impl.ComplexTypeImpl cannot be cast to class com.sun.xml.xsom.impl.SimpleTypeImpl (com.sun.xml.xsom.impl.ComplexTypeImpl and com.sun.xml.xsom.impl.SimpleTypeImpl are in unnamed module of loader 'app')
[WARNING] 	at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:410)
[WARNING] 	at org.apache.cxf.tools.common.toolspec.ToolRunner.runTool(ToolRunner.java:105)
[WARNING] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:113)
[WARNING] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:86)
[WARNING] 	at org.apache.cxf.maven_plugin.wsdl2java.ForkOnceWSDL2Java.main(ForkOnceWSDL2Java.java:51)
[WARNING] Caused by: java.lang.ClassCastException: class com.sun.xml.xsom.impl.ComplexTypeImpl cannot be cast to class com.sun.xml.xsom.impl.SimpleTypeImpl (com.sun.xml.xsom.impl.ComplexTypeImpl and com.sun.xml.xsom.impl.SimpleTypeImpl are in unnamed module of loader 'app')
[WARNING] 	at com.sun.tools.xjc.addon.krasa.JaxbValidationsPlugins.processAttribute(JaxbValidationsPlugins.java:732)
[WARNING] 	at com.sun.tools.xjc.addon.krasa.JaxbValidationsPlugins.run(JaxbValidationsPlugins.java:158)
[WARNING] 	at com.sun.tools.xjc.model.Model.generateCode(Model.java:262)
[WARNING] 	at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.bind(SchemaCompilerImpl.java:255)
[WARNING] 	at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.bind(SchemaCompilerImpl.java:67)
[WARNING] 	at org.apache.cxf.tools.wsdlto.databinding.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:445)
[WARNING] 	at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.generateTypes(WSDLToJavaContainer.java:711)
[WARNING] 	at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.processWsdl(WSDLToJavaContainer.java:259)
[WARNING] 	at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:156)
[WARNING] 	at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:402)
[WARNING] 	... 4 more
```

If i remove the krasa-jaxb-tools dependency and the extra args for XJsr303Annotations the code generation works again.

Dependencies used:

- krasa-jaxb-tools       - 2.2
- cxf-codegen-plugin - 4.0.4
- jakarta.xml.bind-api - 4.0.2
- jakarta.xml.ws-api    - 4.0.1
- jaxws-rt                    - 4.0.2

Is there some workaround for this problem?

**Comment by fillumina** [comment]
I have just deployed on maven central a new version that should have addressed this bug. Could you please check again? Thanks

**Comment by gianluca1606** [comment]
> I have just deployed on maven central a new version that should have addressed this bug. Could you please check again? Thanks

My first Feedback is positive: The error seems to be gone :)
Thank you for the effort!

**Comment by fillumina** [comment]
Thanks but unfortunately I have discovered some other regressions and I am working on them. A new bug fix version should be out soon.

**Comment by gianluca1606** [comment]
> Thanks but unfortunately I have discovered some other regressions and I am working on them. A new bug fix version should be out soon.


Okay so i tried to keep our projects up to date, but unfortunately in one project i got the error again with the 2.3.2 Version. 
The conditions are the same from the inital issue, just the krasa-jaxb-tools has changed to 2.3.2. I also tried the 2.3.1 and it does not work either. 


Going back to 2.3 makes it work. 


So probably something "broke" between the 2.3 and the 2.3.1 version.

**Comment by fillumina** [comment]
Hello @gianluca1606 ,
I've created a test project in [krasa-issue13](https://github.com/fillumina/krasa-issue13) with cxf-codegen-plugin 4.0.4, JDK 17 and all the latest dependencies and it seems to work. Could you please point out where and how the error happens maybe using krasa-issue13 or some other test of yours?
Thanks
