### ISSUE TITLE
`Facet#targetNamespaceEquals` should default to `true`

### ISSUE THREAD

**Issue by Venorcis** [fillumina/krasa-jaxb-tools#14]
In v2.2, `@Valid` was always added. Now in v2.3, if there is no `targetNamespace` option given, the annotation is no longer added.
I believe `Facet#targetNamespaceEquals` should default to `true` if the option is not set to retain the 2.2 behavior.
We have some `xsd` files (out of our control) without any namespace atm. that lead to classes no longer being validated.

**Comment by fillumina** [comment]
You are right. I am fixing it and will publish a 2.3.1 version soon.
Thanks

**Comment by Venorcis** [comment]
Awesome, thanks @fillumina. Any ETA for 2.3.1 appearing on Maven?
