### ISSUE TITLE
Possibility to add numeric annotations to strings

### ISSUE THREAD

**Issue by maddyvinnakota** [fillumina/krasa-jaxb-tools#18]
Hello,
Thanks for your amazing library.

Recently I upgraded to 2.3.5, and I noticed that now there are no more numeric annotations generated for String data types. I was using 2.2 before and it was adding the numeric annotations to String.
Example:

before with 2.2
```
     @XmlElement(required = true)
    @XmlJavaTypeAdapter(StringAdapter.class)
    @XmlSchemaType(name = "decimal")
    @NotNull
    @Digits(integer = 16, fraction = 6)
    @Pattern.List({
        @Pattern(regexp = "[1-9]\\d*(\\.\\d+)?"),
        @Pattern(regexp = "([1-9]\\d*(\\.\\d+)?)|(0\\.\\d*[1-9]\\d*)")
    })
    protected String grossMass;

```
after with 2.3.5
```
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(StringAdapter.class)
    @XmlSchemaType(name = "decimal")
    @NotNull
    @Pattern(regexp = "([1-9]\\d*(\\.\\d+)?)|(0\\.\\d*[1-9]\\d*)")
    protected String grossMass;
```

The fix for Pattern is great as the one before was not correct. However, with this upgrade we lost Digits annotation. I checked the code of this tool, and indeed these is specific handling based on datatype and hence no longer present this annotation.

My request is, if these is possibility to allow ( restore rather ) these numeric annotations? If I follow the specification of Digits (Jakarta EE 8 Specification APIs), it seems to support String type as well.

https://jakarta.ee/specifications/platform/8/apidocs/javax/validation/constraints/digits

```
@Target(value={METHOD,FIELD,ANNOTATION_TYPE,CONSTRUCTOR,PARAMETER,TYPE_USE})
 @Retention(value=RUNTIME)
 @Repeatable(value=Digits.List.class)
 @Documented
 @Constraint(validatedBy={})
public @interface Digits
The annotated element must be a number within accepted range.
Supported types are:

BigDecimal
BigInteger
CharSequence
byte, short, int, long, and their respective wrapper types
null elements are considered valid.
```
Same request for DecimalMax/DecimalMin

I have identified the changes in the tool, ready to create a merge request if you agree.

Thank you very much for your thoughts on this.
Madhava Vinnakota

**Comment by fillumina** [comment]
Hi @maddyvinnakota,
yeah by any means, if you have a pull request ready, go for it. 
Thanks.

**Comment by fillumina** [comment]
Hi @maddyvinnakota,
I am creating a test to validate your change but I have noticed that the `string` type in `XSD` cannot accept `fractionDigits` or `totalDigits` resstrictions (even though the Java `@Digits` annotation can be applied to `String`s) so the change seems to me quite unnecessary. Am I correct? It seems I am missing something, could you please add the XSD snippet that genereted the Java code in your first post?
Thanks

https://www.w3.org/TR/xmlschema-2/#string

**Comment by maddyvinnakota** [comment]
Hi,
XSD indeed does not allow such mixup. However I mentioned in the pull request the scenarios (may be rare, depends on usage) https://github.com/fillumina/krasa-jaxb-tools/pull/19#issue-2598129168 
The requested change simply restores original functionality of this tool in a way. Hope it it helps

**Comment by fillumina** [comment]
Hi, 
it makes sense and doesn't hurt other use cases. I'm just figuring out a way to test it.

**Comment by fillumina** [comment]
It should be ok now, I'll fix the other issues and release.
