### ISSUE TITLE
Pattern generates a List of duplicate patterns, if @size is also present. 

### ISSUE THREAD

**Issue by chin1085** [fillumina/krasa-jaxb-tools#8]
Generated duplicate patterns:
    @NotNull
    @Size(max = 70)
    @Pattern.List({
        @Pattern(regexp = ".{1,70}"),
        @Pattern(regexp = ".{1,70}")
    })
    protected String streetAndNumber;

**Comment by fillumina** [comment]
Could you please check against the new 2.3 version please?
Thanks

**Comment by fillumina** [comment]
I have released yesterday, strangely it took some time to appear but now it is listed on maven central:
https://mvnrepository.com/artifact/com.fillumina/krasa-jaxb-tools/2.3.1

**Comment by fillumina** [comment]
I have just added a test that prove the bug fixed.
