### ISSUE TITLE
Is it possible to use this with Mojohaus' jaxb2-maven-plugin?

### ISSUE THREAD

**Issue by senahornby** [fillumina/krasa-jaxb-tools#9]
The jaxb2-maven-plugin works with later versions of Java as far as I'm aware. I am using it in my JDK17 project right now and have had no issues with it.

Here is their site: http://mojo.codehaus.org/jaxb2-maven-plugin/

I know that on the old krasa-jaxb-tools, someone asked about using it with jaxb2-maven-plugin in 2015 as shown [here](https://github.com/krasa/krasa-jaxb-tools/issues/36). But that was seven years ago and obviously configurations and JDKs have changed.

If it is possible to use this with jaxb2-maven-plugin, could you please provide an example of how to configure the pom? Thanks!

**Comment by senahornby** [comment]
So I should clarify that I was actually able to get this working


              <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jaxb2-maven-plugin</artifactId>
                <version>3.1.0</version>
                <dependencies>
                    <dependency>
                        <groupId>com.fillumina</groupId>
                        <artifactId>krasa-jaxb-tools</artifactId>
                        <version>2.2</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>project</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                        <configuration>
                            <xjbSources>
                                <xjbSource>${project.basedir}/src/main/resources/bindings-file.xjb</xjbSource>
                            </xjbSources>
                            <sources>
                                <source>${project.basedir}/src/main/resources/source-file.xsd</source>
                            </sources>
                            <packageName>package.name.here</packageName>
                            <arguments>
                                <argument>-XJsr303Annotations</argument>
                                <argument>-XJsr303Annotations:JSR_349=true</argument>
                                <argument>-XJsr303Annotations:verbose=false</argument>
                                <argument>-XJsr303Annotations:validationAnnotations=jakarta</argument>
                                <argument>-XJsr303Annotations:generateNotNullAnnotations=true</argument>
                            </arguments>
                        </configuration>
                    </execution>
                  </executions>
                </plugin>
                    
It was pretty straightforward. Just need to make sure jaxb tools is a dependency of the plugin, then add the arguments under the configuration.

**Comment by fillumina** [comment]
Thank you! I have updated the https://github.com/fillumina/krasa-jaxb-tools-example example project with an example of this plugin too.
